name: Actualizador
on:
  workflow_dispatch:
  page_build:
  push:
jobs:
  deployment:
      runs-on:
        - self-hosted
      steps:
        - uses: actions/checkout@v3
        - name: Detención y eliminar informacion docker anterior
          run: |
            sudo docker stop apidoc-rest-n-link-deploy
            sudo docker rm apidoc-rest-n-link-deploy
            sudo docker image rm apidoc-rest-n-link-image
          continue-on-error: true
        - name: comienza
          run: | 
            sudo docker build --no-cache -t apidoc-rest-n-link-image .
            sudo docker run -d --name apidoc-rest-n-link-deploy --network bridge -p 3106:3101 apidoc-rest-n-link-image
